# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"


[[constraint]]
  name = "github.com/blang/semver"
  version = "3.5.1"

[[constraint]]
  branch = "master"
  name = "github.com/dustin/go-humanize"

[[constraint]]
  branch = "master"
  name = "github.com/flynn/json5"

[[constraint]]
  branch = "master"
  name = "github.com/go-errors/errors"

[[constraint]]
  name = "github.com/mattn/go-isatty"
  version = "0.0.3"

[[constraint]]
  name = "github.com/mattn/go-runewidth"
  version = "0.0.2"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  branch = "master"
  name = "github.com/sergi/go-diff"

[[constraint]]
  branch = "master"
  name = "github.com/yuin/gopher-lua"

[[constraint]]
  branch = "master"
  name = "github.com/zyedidia/clipboard"

[[constraint]]
  branch = "master"
  name = "github.com/zyedidia/glob"

[[constraint]]
  branch = "master"
  name = "github.com/zyedidia/tcell"

[[constraint]]
  branch = "v2"
  name = "gopkg.in/yaml.v2"

[[constraint]]
  name = "layeh.com/gopher-luar"
  version = "1.0.1"
